url: http://honnet.github.io
baseurl:

# Site Settings
title: Cedric Honnet
description: "Interhacktivity, Arts, Embedded Systems"
keywords: "HCI, Human computer interaction, embedded systems, robotics, sensors, arts & tech, wearable, IoT, hackerspaces, augmented humans, music tech, custom instruments"
google-tracking-id:

# Log Settings
# Default log thumbnail image.
log-img: "img/timeline/log.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
